---
name: Template-Provider-DBIC
version: 0.01
author: []
abstract: Load templates using DBIx::Class.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Date::Parse: 0
  Template: 2.15
  Test::More: 0
  version: 0
build_requires:
  DBD::SQLite: 1.11
  DBIx::Class: 0
provides:
  Template::Provider::DBIC:
    file: lib/Template/Provider/DBIC.pm
    version: 0.01
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
